.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "SETUP\-DIST" "8" "January 2020" "setup-dist" "setup-dist Manual"
.SH "NAME"
\fBsetup\-dist\fR \- Connection Wizard
.SH "SYNOPSIS"
\fBsetup\-dist\fR
.SH "DESCRIPTION"
Asks in which environment you are using the derivative distribution, informs about various situations, helps to enable Tor in Tor config\.
.SH "EXAMPLE"
\fBsetup\-dist\fR
.SH "SKIP FILES"
Useful to custom builds and derivative distributions\.
.P
\fB/usr/share/setup\-dist/status\-files/disclaimer\.skip\fR
.P
Prevents showing Derivative Distribution's disclaimer\.
.P
\fB/usr/share/setup\-dist/status\-files/first_use_check\.skip\fR
.P
Prevents showing first run notice\.
.SH "SKIP FILES USAGE EXAMPLES"
\fBsudo mkdir \-\-parents /usr/share/setup\-dist/status\-files\fR
.P
\fBsudo touch /usr/share/setup\-dist/status\-files/repository\-dist\.skip\fR
.P
\fBsudo touch /usr/share/setup\-dist/status\-files/disclaimer\.skip\fR
.P
\fBsudo touch /usr/share/setup\-dist/status\-files/first_use_check\.skip\fR
.SH "WWW"
https://www\.whonix\.org
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
