#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

source "/usr/libexec/setup-dist/shared"

#MSG=""

#TITLE="I want to hide Whonix from my ISP."

#dialog_wrapper --title "$TITLE" --msgbox "$MSG" 640 480

## Same message as ft_m_3.
ft_m_3

exit 0
