#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

source "/usr/libexec/setup-dist/shared"

MSG="
You can always enter setup-dist again, by starting: setup-dist
"

TITLE="setup-dist - Cancel."

dialog_wrapper --title "$TITLE" --msgbox "$MSG" 640 480

true "INFO: Ok, exit 1, so setup-dist will end."
## Signal for setup-dist to break the while loop.
exit 1
