#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

source "/usr/libexec/setup-dist/shared"

MSG='
(You can scroll down using the arrow key).

Less sophisticated censors prevent users from accessing the Tor network by blocking connections to known relays. "Bridge relays" help these users access Tor by not being in the same public lists as normal relays.

Sophisticated censors can only be circumvented with private obfuscated bridges.

Because there is NOT a 100%  way to hide Tor, Whonix does NOT recommend using Tor if you fear detection.


Configure Whonix to Use a Bridge
--------------------------------

Press Enter to close this message, then select Exit. You must manually find and add the bridges to /usr/local/etc/torrc.d/50_user.conf.

You can open /usr/local/etc/torrc.d/50_user.conf in the terminal:
    sudo nano /usr/local/etc/torrc.d/50_user.conf

Or, if you are using a graphical Whonix-Gateway:
    Start Menu -> System -> Tor User Config


Configure Whonix to a Use a VPN
-------------------------------

Where Tor is censored but VPNs are allowed, you can hide your Tor connection inside a VPN connection. To the censors, your internet traffic will look like an encrypted VPN connection. The VPN will then send your Tor traffic onward to the first Tor relay.

If you are using Whonix-Gateway inside VirtualBox, configure your VPN software inside the host operating system. Your VPN provider will have instructions for you to follow and possibly custom software to help you connect.

However, you MUST configure your VPN software (whether custom or built into your operating system) to send all internet traffic through the VPN connection, and you MUST configure your VPN software to block all internet traffic if the VPN is suddenly disconnected. Additionally, you MUST NOT chose PPTP as your encryption even if your VPN allows it. Improperly configured VPN software will reveal your Tor connection to the censors.

Whonix recommends a VPN provider who is serious about privacy and is outside the reach of your censors.
'

TITLE="setup-dist - Tor is censored or dangerous in my area."

dialog_wrapper --title "$TITLE" --msgbox "$MSG" 640 480

exit 0
