#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

source "/usr/libexec/setup-dist/shared"

MSG='
If your firewall works by blocking ports, then you can tell Tor to only use the ports that your firewall permits by adding "FascistFirewall 1" to your Tor configuration file.

By default, when you set this Tor assumes that your firewall allows only port 80 and port 443 (HTTP and HTTPS respectively).

If you want to be more fine-grained with your controls, you can also use the ReachableAddresses config options, e.g.:
ReachableDirAddresses *:80
ReachableORAddresses *:443

You can open torrc by using editor nano.

   sudo nano /usr/local/etc/torrc.d/50_user.conf

Or, if you are using a graphical Whonix-Gateway.

    Start Menu -> System -> Tor User Config

Tor Manual:
https://www.torproject.org/docs/tor-manual.html.en
'

TITLE="setup-dist - My firewall only lets me connect to certain ports."

dialog_wrapper --title "$TITLE" --msgbox "$MSG" 640 480

exit 0
