#!/bin/bash

## Copyright (C) 2012 - 2021 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

#set -x

source "/usr/libexec/setup-dist/shared"

MSG='
(You can scroll down using the arrow key.)

Some Internet Service Providers prevent users from accessing the Tor network by blocking connections to known relays. "Bridge relays" help these users access Tor by not being listed in the same public directories as normal relays. Less sophisticated censors have trouble censoring all of them.

Sophisticated censors can only be circumvented with private obfuscated bridges. Someone you trust must run a bridge configured with obfsproxy (to help avoid detection) and the option "PublishServerDescriptor 0" (to not be listed by The Tor Project). However, since even private obfuscated bridges can ultimately be detected, Whonix does NOT recommend using Tor where its detection could result in significant harm.


Finding Bridges
---------------

You can find the IP address of public bridges at:
https://bridges.torproject.org/bridges

If you can not reach the URL, send an email (from a gmail.com or yahoo.com account only) to bridges@torproject.org with "get bridges" in the message body.

Whonix recommends using "bridge obfs3" IP addresses only.


Configure Whonix to Use Bridges
-------------------------------

Press enter to close this message, then cancel the connection wizard by using Cancel button in the main menu. You must manually add the bridge(s) IP address to /usr/local/etc/torrc.d/50_user.conf.

You can open /usr/local/etc/torrc.d/50_user.conf in the terminal:

    sudo nano /usr/local/etc/torrc.d/50_user.conf

Or, if you are using a graphical Whonix-Gateway:

    Start Menu -> System -> Tor User Config
'

TITLE="setup-dist - Tor is censored in my area."

dialog_wrapper --title "$TITLE" --msgbox "$MSG" 640 480

exit 0
