#!/usr/bin/python3 -u

## Copyright (C) 2024 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

from anon_connection_wizard import tor_status

tor_status.set_enabled()
