#!/bin/bash

## Copyright (C) 2012 - 2022 ENCRYPTED SUPPORT LP <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

dialog_wrapper() {
   if tty --quiet ; then
      dialog "$@"
   else
      echo "$TITLE"
      echo "$MSG"
   fi
}
