#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

maximize_window() {
   ## Needs to be a short title. For example "whonix-autosetup" is one char too
   ## long, while "whonixsetup" works.
   title="$(basename "$0")"
   if [ ! -f /usr/lib/msgcollector/msgwmctrl ]; then
      return 0
   fi
   true "INFO: Waiting for window title \"$title\" to appear."
   source /usr/lib/msgcollector/msgwmctrl
   output_wait_for_window "$title"
   ## Deactivate eventual trap from msgwmctrl.
   trap "" ERR
   true "INFO: Maximizing window title \"$title\"."
   sleep 1 &
   wait "$!"
   wmctrl -b add,maximized_vert,maximized_horz -r "$title"
   true "INFO: Maximized window title \"$title\"."
   sleep 1 &
   wait "$!"
}

cat /etc/motd

maximize_window
sudo whonixsetup

true "INFO: Feel free to close this window."

sleep 86400
