#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Gets started by /etc/xdg/autostart/whonixsetup.desktop.

set -x

whonixsetup_start_x_version_maybe() {
   if [ -x "/usr/bin/whonix-setup-wizard" ]; then
      true "/usr/bin/whonix-setup-wizard is executable. Starting..."
      xhost +local:root
      sudo whonix-setup-wizard & disown
      true "Started. Exiting."
      exit 0
   fi
   true "/usr/bin/whonix-setup-wizard is not executable or not installed. Maybe falling back to cli version..."
}

motd_show_maybe() {
   if [ -f /etc/motd ]; then
      cat /etc/motd
   fi
}

maximize_window_maybe() {
   if [ ! -f /usr/lib/msgcollector/msgwmctrl ]; then
      return 0
   fi
   source /usr/lib/msgcollector/msgwmctrl

   true "INFO: Getting own window title..."
   ## sets: own_window_title
   get_own_window_title
   ## Deactivate eventual trap from msgwmctrl.
   trap "" ERR
   if [ "$own_window_title" = "false" ]; then
      true "ERROR: Failed to find out own window title."
      return 0
   fi
   title="$own_window_title"

   true "INFO: Waiting for window title \"$title\" to appear..."
   ## sets: window_title_found
   output_wait_for_window "$title"
   ## Deactivate eventual trap from msgwmctrl.
   trap "" ERR
   if [ "$window_title_found" = "false" ]; then
      true "ERROR: window title \"$title\" did not appear."
      return 0
   fi

   true "INFO: Maximizing window title \"$title\"..."
   sleep 1 &
   wait "$!"
   wmctrl -b add,maximized_vert,maximized_horz -r "$title"
   true "INFO: Maximized window title \"$title\"."
   sleep 1 &
   wait "$!"
}

whonixsetup_sleep() {
   true "INFO: Feel free to close this window."
   sleep 86400
}

whonixsetup_start_cli_version() {
   motd_show_maybe
   maximize_window_maybe
   true "Waiting a few seconds before starting whonixsetup."
   ## This is required because `dialog`'s text may become unreadable when the
   ## window was maximized after `dialog` was run.
   sleep 3 &
   wait "$!"
   true "Starting whonixsetup."
   sudo whonixsetup --x
   whonixsetup_sleep
}

if [ -f "/usr/share/anon-gw-base-files/gateway" ]; then
   source /usr/lib/anon-shared-helper-scripts/tor_enabled_check

   ## Check if Tor is enabled.
   ## sets: TOR_ENABLED
   check_tor_enabled_do

   if [ "$TOR_ENABLED" = "0" ]; then
      whonixsetup_start_x_version_maybe
      whonixsetup_start_cli_version
      exit 0
   fi
else
   if [ -f "/var/lib/whonix/do_once/whonixsetup.done" ]; then
      ## /var/lib/whonix/do_once/whonixsetup.done exists.
      ## whonixsetup already finished earlier, exit.
      exit 0
   else
      ## /var/lib/whonix/do_once/whonixsetup.done does not exist.
      ## whonixsetup not finished yet, continue.
      whonixsetup_start_x_version_maybe
      whonixsetup_start_cli_version
      exit 0
   fi
fi

exit 0
