#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Gets started by /etc/xdg/autostart/whonixsetup.desktop.

set -x

maximize_window() {
   ## Needs to be a short title. For example "whonix-autosetup" is one char too
   ## long, while "whonixsetup" works.
   title="$(basename "$0")"
   if [ ! -f /usr/lib/msgcollector/msgwmctrl ]; then
      return 0
   fi
   true "INFO: Waiting for window title \"$title\" to appear."
   source /usr/lib/msgcollector/msgwmctrl
   output_wait_for_window "$title"
   ## Deactivate eventual trap from msgwmctrl.
   trap "" ERR
   true "INFO: Maximizing window title \"$title\"."
   sleep 1 &
   wait "$!"
   wmctrl -b add,maximized_vert,maximized_horz -r "$title"
   true "INFO: Maximized window title \"$title\"."
   sleep 1 &
   wait "$!"
}

if [ -f "/usr/share/anon-ws-base-files/workstation" ]; then
   if [ -f "/var/lib/whonix/do_once/whonixsetup.done" ]; then
      ## /var/lib/whonix/do_once/whonixsetup.done exists.
      ## whonixsetup already finished earlier, exit.
      exit 0
   else
      ## /var/lib/whonix/do_once/whonixsetup.done does not exist.
      ## whonixsetup not finished yet, continue.
      cat /etc/motd
      maximize_window
      sudo whonixsetup
      true "INFO: Feel free to close this window."
      sleep 86400
      exit 0
   fi
fi

source /usr/lib/anon-shared-helper-scripts/tor_enabled_check

## Check if Tor is enabled.
## sets: TOR_ENABLED
check_tor_enabled_do

if [ "$TOR_ENABLED" = "0" ]; then
   cat /etc/motd
   maximize_window
   sudo whonixsetup
   true "INFO: Feel free to close this window."
   sleep 86400
   exit 0
fi

exit 0
