#!/bin/bash

## Copyright (C) 2021 - 2021 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#### meta start
#### project Whonix and Kicksecure
#### category usability
#### description
## Simple wrapper that runs `dsudo easyorca-root`.
#address 10.152.152.10
#netmask 255.255.192.0
#### meta end

dsudo easyorca-root
