#!/bin/bash

## Copyright (C) 2021 - 2021 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Close stdin so setup-dist will run non-interactive.
exec 0<&-

setup-dist "$@"
