#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

TITLE="Important Information About Whonix Part 1/2 | Wichtige Informationen zu Whonix Teil 1/2 (whonixsetup)"

MSG='
ENG: Please do NOT continue unless you understand everything!

ENG: Welcome to Whonix!

ENG: This is not the usual blah blah blah but fact.

ENG: Whonix is experimental software. Do not rely on it for strong anonymity.

ENG: Whonix is created by volunteers in their spare time.

ENG: Whonix was created by self-taught hobbyists in their spare time, without the backing of any particular formal certification or training.

ENG: Although Whonix attempts to be as usable as possible, there are many ways in which it fails.

ENG: Whonix is in English. Do not use Whonix without excellent knowledge of the English language. Misunderstandings have consequences.

ENG: Whonix is based on other software, including GNU/Linux, Debian, and virtualization. Do not rely on Whonix without working knowledge of these technologies.
'

dialog --title "$TITLE" --defaultno --yes-label "Understood / Verstanden" --no-label "Not understood / Nicht verstanden" --yesno "$MSG" 640 480

ret="$?"

if [ "$ret" = "1" ]; then
   /sbin/poweroff
   ## Endless loop.
   while true; do
      sleep 1
   done
fi

TITLE="Important Information About Whonix Part 2/2 | Wichtige Informationen zu Whonix Teil 2/2 (whonixsetup)"

MSG='
ENG: Please do NOT continue unless you understand everything!

ENG: The documentation available on Whonix.org is a crash course in anonymity, privacy, and security on the Internet. Whonix is a technological means to anonymity, but staying anonymous is not just a technological problem: No tool is enough to keep you safe. Anonymity is a complex problem without an easy solution, and security is only as strong as its weakest link, often the user. The more you know, the safer you can be.

ENG: Whonix is a compilation of software packages, each under its own copyright and license. The exact license terms for each program are described in the individual files in /usr/share/doc/*/copyright.

ENG: The compilation is made available under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

ENG: Whonix is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, to the extent permitted by applicable law. See the GNU General Public License for more details.

ENG: Whonix is free of charge.

ENG: Whonix is a derivative of Debian GNU/Linux.

ENG: Whonix is produced independently of, with no guarantee from, The Tor Project.
'

dialog --title "$TITLE" --defaultno --yes-label "Understood / Verstanden" --no-label "Not understood / Nicht verstanden" --yesno "$MSG" 640 480

ret="$?"

if [ "$ret" = "1" ]; then
   /sbin/poweroff
   ## Endless loop.
   while true; do
      sleep 1
   done
fi
