#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

source "/usr/lib/whonixsetup_/shared"

MSG="
You can always enter whonixsetup again, by starting: sudo whonixsetup
"

TITLE="whonixsetup - Cancel."

dialog_wrapper --title "$TITLE" --msgbox "$MSG" 640 480

true "INFO: Ok, exit 1, so whonixsetup will end."
## Signal for whonixsetup to break the while loop.
exit 1
