#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail
set -o errtrace

error_handler() {
   local MSG="\
###########################################################
## Something went wrong. Please report this bug!
##
## BASH_COMMAND: $BASH_COMMAND
###########################################################\
"
   echo "$MSG"
   exit 1
}

trap "error_handler" ERR

tor_action_exit_code_check() {
   if [ ! "$exit_code" = "0" ]; then
      TITLE="whonixsetup - Error!"
      MSG="
    sudo service tor@default $service_action

returned exit code $exit_code, which means Tor does NOT work.
Maybe your Whonix-Gateway has only one network card attached? Most likely there
is something wrong with your /etc/tor/torrc.

You can open /etc/tor/torrc in the terminal:
    sudo nano /etc/tor/torrc

Or, if you are using a graphical Whonix-Gateway:
    Start Menu -> Applications -> /etc/tor/torrc

Running:

   sudo service tor@default restart

might help with troubleshooting.
"
      dialog --title "$TITLE" --msgbox "$MSG" 640 480
      true "INFO: Ok, exit 1, so whonixsetup will end."
      exit 1
   fi
}

## root check
if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This must be run as root (sudo)!"
    exit 1
fi

MSG='
Connect to the public Tor network now?

By default, Tor does not try to hide the fact that you are using it. If this concerns you, select "No" now. Then, select the menu option "Tor is censored or dangerous in my area" and follow the instructions.

Ultimately, the best protection is a social approach: the more Tor users there are near you and the more diverse their interests, the safer it will be to use it. Convince other people to use Tor!

Note: whonixsetup enables Tor networking by uncommenting "DisableNetwork 0" in /etc/tor/torrc.
'

TITLE="whonixsetup - Connect to the Tor network."

exit_code="0"
dialog --title "$TITLE" --yesno "$MSG" 640 480 || { exit_code="$?" ; true; };

if [ ! "$exit_code" = "0" ]; then
   ## Back to main menu.
   exit 0
fi

## Check if Tor was already enabled.
## This is to prevent getting ed from failing.
already_commented_in="0"
while read -r LINE; do
   if [ "$LINE" = 'DisableNetwork 0' ]; then
      already_commented_in="1"
      dialog --title "whonixsetup - Success!" --msgbox 'Tor networking should already be enabled.

Note: whonixsetup enables Tor networking by uncommenting "DisableNetwork 0" in /etc/tor/torrc There is no need to this multiple times, and it is probably not the cause of network problems. You can manually check if "DisableNetwork 0" is uncommented in /etc/tor/torrc.

Press Enter to restart Tor and check its status.
' 640 480
      break
   fi
done < "/etc/tor/torrc"

if [ "$already_commented_in" = "0" ]; then
   ## Comment in DisableNetwork 0 in /etc/tor/torrc.
   exit_code="0"
   ed -s /etc/tor/torrc <<< $',s/\#DisableNetwork 0/DisableNetwork 0/g\nw' || { exit_code="$?" ; true; };

   ## Ensure changes get written to the disk right now.
   sync

   if [ ! "$exit_code" = "0" ]; then
      TITLE="whonixsetup - Info"

      MSG='
Could not comment "DisableNetwork 0" in /etc/tor/torrc
Have you commented or completely removed "DisableNetwork 0" from /etc/tor/torrc?

Press Enter to restart Tor and check its status.
'

   else
      TITLE="whonixsetup - Info"

      MSG="
Tor networking has been enabled in /etc/tor/torrc

Press Enter to restart Tor and check its status.
"
   fi

   dialog --title "$TITLE" --msgbox "$MSG" 640 480
fi

service_action="restart"
exit_code="0"
service tor@default "$service_action" >/dev/null || { exit_code="$?" ; true; };
sync
sleep 1
tor_action_exit_code_check

exit_code="0"
service_action="status"
service tor@default "$service_action" || { exit_code="$?" ; true; };
sync
sleep 1
tor_action_exit_code_check

TITLE="whonixsetup - Success!"

MSG="
Tor was successfully restarted.

Press Enter to run whonixcheck and exit.
"

dialog --title "$TITLE" --msgbox "$MSG" 640 480

## Start whonixcheck.
exit_code="0"
ft_m_end || { exit_code="$?" ; true; };

true "INFO: Ok, exit 1, so whonixsetup will end."
exit 1
