#!/bin/bash

## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#MSG=""

#TITLE="I want to hide Whonix from my ISP."

#dialog --title "$TITLE" --msgbox "$MSG" 640 480

## Same message as ft_m_3.
ft_m_3

exit 0
