#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x
set -o pipefail

error_handler() {
   local MSG="\
###########################################################
## Something went wrong. Please report this bug!
##
## BASH_COMMAND: $BASH_COMMAND
###########################################################\
"
   echo "$MSG"
   exit 1
}

trap "error_handler" ERR

## root check
if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This must be run as root (sudo)!"
    exit 1
fi

if [ -f "/usr/share/anon-gw-base-files/gateway" ]; then
   timesync_pre="/usr/lib/timesync/timesync_pre"
   timesync_test_f_exit_code="0"
   test -f "$timesync_pre" || { timesync_test_f_exit_code="$?" ; true; };
   if [ -x "$timesync_pre" ]; then
      true "INFO: Opening timesync progress bar..."
      ## When Tor was not enabled when /usr/bin/sdwdate started
      ## /usr/lib/timesync/timesync_pre then timesync_pre exited without starting a
      ## progress bar (for better look and feel during first start, not needlessly
      ## start the timesync waiting progress bar if Tor has not been enabled yet in
      ## whonixsetup). Let's catch up on that and let /usr/lib/timesync/timesync_pre
      ## start the timesync progress bar.
      ##
      ## ">/dev/null 2>/dev/null" to hide duplicate `echo`s, because `sdw_pre` will
      ## use `msgcollector`.
      ## (Developer comment: When modifying the next line, also consider modifying
      ##                     /etc/sdwdate.d/31_timesync_plugin.)
      "$timesync_pre" --autostart --mode "startup" >/dev/null 2>/dev/null & disown
      ## Wait. Only for the look and feel. Prevent mixing up timesync message with whonixcheck.
      sleep 5 &
      wait "$!"
      true "INFO: Opened timesync progress bar."
      true "INFO: (This is only of interest when Tor was disabled while Whonix was booted)."
   else
      if [ "$timesync_test_f_exit_code" = "0" ]; then
         true "INFO: Skipping opening timesync progress bar, because $timesync_pre is not executable."
      else
         true "INFO: Skipping opening timesync progress bar, because timesync progress bar is unavailable."
      fi
   fi
fi

check_bin="whonixcheck"
check_bin_command_v_exit_code="0"
check_bin_path="$(command -v "$check_bin" 2>/dev/null)" || { check_bin_command_v_exit_code="$?" ; true; };

exit_code="0"
if [ -x "$check_bin_path" ]; then
   true "INFO: Starting $check_bin..."

   sudo -u user $check_bin || { exit_code="$?" ; true; };

   true "INFO: End of $check_bin. You can always start $check_bin again with:
    $check_bin"
else
   if [ "$check_bin_command_v_exit_code" = "0" ]; then
      true "INFO: Skipping starting $check_bin, because $check_bin_path is not executable."
   else
      true "INFO: Skipping starting $check_bin, because $check_bin is unavailable."
   fi
fi

exit "$exit_code"
