#!/bin/bash

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

MSG='
(You can scroll down using the arrow key).

You must manually edit /usr/local/etc/torrc.d/50_user.torrc for Tor to navigate through your firewall or proxy.

Press Enter to close this message, then select Exit.

You can open /usr/local/etc/torrc.d/50_user.torrc in the terminal:
    sudo nano /usr/local/etc/torrc.d/50_user.torrc

Or on the desktop:
    Start Menu -> Applications -> Tor Config File
'

TITLE="whonixsetup - I use proxy or firewall settings to connect to the internet."

dialog --title "$TITLE" --msgbox "$MSG" 640 480

exit 0
