#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x
set -o pipefail
set -o errtrace

error_handler() {
   local MSG="\
###########################################################
## Something went wrong. Please report this bug!
##
## BASH_COMMAND: $BASH_COMMAND
###########################################################\
"
   echo "$MSG"
   exit 1
}

trap "error_handler" ERR

## root check
if [ "$(id -u)" != "0" ]; then
    echo "$0 ERROR: This must be run as root (sudo)!"
    exit 1
fi

maybe_start_systemcheck() {
   systemcheck_bin="systemcheck"
   systemcheck_bin_command_v_exit_code="0"
   systemcheck_bin_path="$(command -v "$systemcheck_bin" 2>/dev/null)" || { systemcheck_bin_command_v_exit_code="$?" ; true; };

   if ! tty --quiet ; then
      echo "INFO: Skipping starting $systemcheck_bin, because started non-interactive."
      echo "INFO: Runnning $systemcheck_bin recommended!"
      return 0
   fi

   if [ ! "$systemcheck_bin_command_v_exit_code" = "0" ]; then
      echo "INFO: Skipping starting $systemcheck_bin, because $systemcheck_bin is unavailable."
      return 0
   fi
   if [ ! -x "$systemcheck_bin_path" ]; then
      echo "INFO: Skipping starting $systemcheck_bin, because $systemcheck_bin_path is not executable."
      return 0
   fi
   echo "INFO: Starting $systemcheck_bin..."
   if [ "$SUDO_USER" = "" ]; then
      sudo --non-interactive --set-home -u user "$systemcheck_bin" || { exit_code="$?" ; true; };
   else
      sudo --non-interactive --set-home -u "$SUDO_USER" "$systemcheck_bin" || { exit_code="$?" ; true; };
   fi
   echo "INFO: End of $systemcheck_bin. You can always start $systemcheck_bin again with:
    $systemcheck_bin"
}

## This is required, otherwise systemcheck would abort.
mkdir --parents "/var/cache/setup-dist/status-files"
touch "/var/cache/setup-dist/status-files/setup-dist.done"

exit_code="0"

maybe_start_systemcheck

exit "$exit_code"
